services:
  mysql:
    image: mysql:8.0
    container_name: smartmall-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartmall
    ports:
      - "3306:3306"
    volumes:
      - smartmall-mysql-data:/var/lib/mysql

volumes:
  smartmall-mysql-data:
