# In produzione NON aggiorniamo la struttura del DB in automatico per evitare perdita di dati.
# Il DB deve essere già pronto o aggiornato tramite script SQL.
spring.jpa.hibernate.ddl-auto=validate

# In produzione non mostriamo le query SQL nella console per ragioni di performance
spring.jpa.show-sql=false