
# CONNESSIONE AL DATABASE MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/smartmall?serverTimezone=UTC
spring.datasource.username=root
#PASWWORD DB:
spring.datasource.password=smartmall
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURAZIONE JPA / HIBERNATE
#Aggiornamento delle tabelle automitico
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nella console (comodo per il debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CONFIGURAZIONE JWT
# ===============================
# Chiave segreta per firmare i token (deve essere lunga almeno 256 bit per sicurezza)
jwt.secret=QuestaEunaChiaveSegretaMoltoLungaESicuraPerIlProgettoSmartMall2026!
# Scadenza del token (es. 24 ore in millisecondi: 86400000)
jwt.expiration=86400000